services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-test
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123StrongPassword!
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
      - ./init.sql:/init.sql
    command: >
      bash -c "
      /opt/mssql/bin/sqlservr &
      sleep 30s &&
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '123StrongPassword!' -C -i /init.sql &&
      wait
      "

volumes:
  mssql-data:
