services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-test
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123StrongPassword!
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
