version: "3.8"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-dev
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "DeinStarkesPasswort123!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./init:/docker-entrypoint-initdb.d
    command: >
      /bin/bash -c "
        /opt/mssql/bin/sqlservr & 
        sleep 20 &&
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'DeinStarkesPasswort123!' -i /docker-entrypoint-initdb.d/init.sql &&
        wait
      "
    restart: unless-stopped

volumes:
  mssql_data:
