// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Line struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Operation struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	ToolID int64  `json:"tool_id"`
}

type Station struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	LineID int64  `json:"line_id"`
}

type Tool struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	StationID int64  `json:"station_id"`
}
